sudo: required
services:
  - docker
before_install:
  - docker build -t pankajchoudhary/react-test -f ./client/Dev.Dockerfile ./client
script:
  - docker run pankajchoudhary/react-test npm run test -- --coverage
after_success:
  - docker build -t pankajchoudhary/multi-nginx -f ./nginx/Dev.Dockerfile ./nginx
  - docker build -t pankajchoudhary/multi-server -f ./server/Dev.Dockerfile ./server
  - docker build -t pankajchoudhary/multi-client -f ./client/Dev.Dockerfile ./client
  - docker build -t pankajchoudhary/multi-worker -f ./worker/Dev.Dockerfile ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push pankajchoudhary/multi-client
  - docker push pankajchoudhary/multi-worker
  - docker push pankajchoudhary/multi-server
  - docker push pankajchoudhary/multi-nginx