sudo: required
services:
  - docker
before_install:
  - docker build -t pankajchoudhary/react-test -f ./client/Dev.Dockerfile ./client
script:
  - docker run pankajchoudhary/react-test npm run test -- --coverage
after_success:
  - docker build -t pankajchoudhary/multi-nginx  ./nginx
  - docker build -t pankajchoudhary/multi-server  ./server
  - docker build -t pankajchoudhary/multi-client  ./client
  - docker build -t pankajchoudhary/multi-worker  ./worker

